# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Setup MariaDB
        # You may pin to the exact commit or the version.
        # uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248
        uses: getong/mariadb-action@v1.1
        with:
          # The port of host
          host port: 3306 # optional, default is 3306
          container port: 3306
          collation server: utf8mb4_unicode_ci
          mariadb version: latest
          # MYSQL_DATABASE - name for the default database that is created
          mysql database: NECos_ci # optional, default is
          # MYSQL_USER - create the specified user with superuser power for created database
          mysql user: NECos # optional, default is
          # MYSQL_PASSWORD - specified superuser password which user is power for created database
          mysql password: necos # optional, default is
      - run: npm ci
      - run: cp -r config.example config
      - run: NODE_ENV=ci npm run migrate:up
      - run: npm run build
      - run: npm run ci --if-present
      - name: "Set up SSH"
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600 ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host deploy
            HostName ssh.imskyyc.xyz
            User deploy
            Port 5622
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
      - name: "Deploy"
        run: ssh deploy 'sudo /bin/systemctl restart necos-beta.service'

